// ============================================================
// Forge App - Sample Data for first-load experience
// ============================================================

import { TimetableEvent, PriorityItem, UserPreferences, DayOfWeek } from "@/types";
import { generateId } from "./utils";

/** Default user preferences */
export const DEFAULT_PREFERENCES: UserPreferences = {
  wakeTime: "06:30",
  sleepTime: "22:30",
  studySessionLength: 50,
  breakLength: 10,
  mealTimes: {
    breakfast: "07:30",
    lunch: "12:30",
    dinner: "18:30",
  },
  travelBuffer: 20,
  theme: "system",
  reminderTiming: 10,
  enableNotifications: true,
  enableFocusMode: false,
  name: "Student",
};

/** Sample baseline timetable events */
export const SAMPLE_EVENTS: TimetableEvent[] = [
  // Monday
  {
    id: generateId(),
    title: "Morning Run",
    day: "Monday",
    startTime: "06:30",
    endTime: "07:15",
    category: "exercise",
    description: "Light cardio to start the day",
  },
  {
    id: generateId(),
    title: "Breakfast",
    day: "Monday",
    startTime: "07:30",
    endTime: "08:00",
    category: "meal",
  },
  {
    id: generateId(),
    title: "Calculus Lecture",
    day: "Monday",
    startTime: "09:00",
    endTime: "11:00",
    category: "class",
    location: "Room 201",
    priority: 8,
  },
  {
    id: generateId(),
    title: "Lunch Break",
    day: "Monday",
    startTime: "12:30",
    endTime: "13:30",
    category: "meal",
  },
  {
    id: generateId(),
    title: "Calculus Study",
    day: "Monday",
    startTime: "14:00",
    endTime: "15:30",
    category: "study",
    priority: 9,
  },
  {
    id: generateId(),
    title: "Physics Lab",
    day: "Monday",
    startTime: "16:00",
    endTime: "18:00",
    category: "class",
    location: "Lab 3",
  },
  {
    id: generateId(),
    title: "Dinner",
    day: "Monday",
    startTime: "18:30",
    endTime: "19:15",
    category: "meal",
  },
  {
    id: generateId(),
    title: "Evening Study",
    day: "Monday",
    startTime: "19:30",
    endTime: "21:30",
    category: "study",
  },
  {
    id: generateId(),
    title: "Wind Down / Sleep",
    day: "Monday",
    startTime: "22:30",
    endTime: "06:30",
    category: "sleep",
  },

  // Tuesday
  {
    id: generateId(),
    title: "Breakfast",
    day: "Tuesday",
    startTime: "07:30",
    endTime: "08:00",
    category: "meal",
  },
  {
    id: generateId(),
    title: "Programming Lecture",
    day: "Tuesday",
    startTime: "08:30",
    endTime: "10:30",
    category: "class",
    location: "CS Building",
  },
  {
    id: generateId(),
    title: "Travel to Library",
    day: "Tuesday",
    startTime: "10:30",
    endTime: "10:50",
    category: "travel",
  },
  {
    id: generateId(),
    title: "Deep Work - Algorithms",
    day: "Tuesday",
    startTime: "11:00",
    endTime: "13:00",
    category: "study",
    priority: 10,
  },
  {
    id: generateId(),
    title: "Lunch",
    day: "Tuesday",
    startTime: "13:00",
    endTime: "14:00",
    category: "meal",
  },
  {
    id: generateId(),
    title: "Statistics Class",
    day: "Tuesday",
    startTime: "14:30",
    endTime: "16:30",
    category: "class",
  },
  {
    id: generateId(),
    title: "Gym Session",
    day: "Tuesday",
    startTime: "17:00",
    endTime: "18:30",
    category: "exercise",
  },
  {
    id: generateId(),
    title: "Dinner",
    day: "Tuesday",
    startTime: "19:00",
    endTime: "19:45",
    category: "meal",
  },
  {
    id: generateId(),
    title: "Review Notes",
    day: "Tuesday",
    startTime: "20:00",
    endTime: "21:30",
    category: "study",
  },
  {
    id: generateId(),
    title: "Sleep",
    day: "Tuesday",
    startTime: "22:30",
    endTime: "06:30",
    category: "sleep",
  },

  // Wednesday
  {
    id: generateId(),
    title: "Breakfast",
    day: "Wednesday",
    startTime: "07:30",
    endTime: "08:00",
    category: "meal",
  },
  {
    id: generateId(),
    title: "Calculus Tutorial",
    day: "Wednesday",
    startTime: "09:00",
    endTime: "10:00",
    category: "class",
  },
  {
    id: generateId(),
    title: "Research & Reading",
    day: "Wednesday",
    startTime: "10:30",
    endTime: "12:30",
    category: "study",
  },
  {
    id: generateId(),
    title: "Lunch",
    day: "Wednesday",
    startTime: "12:30",
    endTime: "13:30",
    category: "meal",
  },
  {
    id: generateId(),
    title: "Group Project Meeting",
    day: "Wednesday",
    startTime: "14:00",
    endTime: "16:00",
    category: "work",
    location: "Study Room B",
  },
  {
    id: generateId(),
    title: "Personal Time",
    day: "Wednesday",
    startTime: "16:30",
    endTime: "18:00",
    category: "personal",
  },
  {
    id: generateId(),
    title: "Dinner",
    day: "Wednesday",
    startTime: "18:30",
    endTime: "19:15",
    category: "meal",
  },
  {
    id: generateId(),
    title: "Programming Practice",
    day: "Wednesday",
    startTime: "20:00",
    endTime: "22:00",
    category: "study",
    priority: 8,
  },
  {
    id: generateId(),
    title: "Sleep",
    day: "Wednesday",
    startTime: "22:30",
    endTime: "06:30",
    category: "sleep",
  },

  // Thursday
  {
    id: generateId(),
    title: "Breakfast",
    day: "Thursday",
    startTime: "07:30",
    endTime: "08:00",
    category: "meal",
  },
  {
    id: generateId(),
    title: "Physics Lecture",
    day: "Thursday",
    startTime: "09:00",
    endTime: "11:00",
    category: "class",
  },
  {
    id: generateId(),
    title: "Travel Home",
    day: "Thursday",
    startTime: "11:00",
    endTime: "11:20",
    category: "travel",
  },
  {
    id: generateId(),
    title: "Lunch",
    day: "Thursday",
    startTime: "12:00",
    endTime: "12:45",
    category: "meal",
  },
  {
    id: generateId(),
    title: "Statistics Study",
    day: "Thursday",
    startTime: "13:00",
    endTime: "15:00",
    category: "study",
    priority: 7,
  },
  {
    id: generateId(),
    title: "Break",
    day: "Thursday",
    startTime: "15:00",
    endTime: "15:30",
    category: "break",
  },
  {
    id: generateId(),
    title: "Physics Study",
    day: "Thursday",
    startTime: "15:30",
    endTime: "17:30",
    category: "study",
    priority: 9,
  },
  {
    id: generateId(),
    title: "Dinner",
    day: "Thursday",
    startTime: "18:30",
    endTime: "19:15",
    category: "meal",
  },
  {
    id: generateId(),
    title: "Evening Wind-down",
    day: "Thursday",
    startTime: "21:00",
    endTime: "22:00",
    category: "personal",
  },
  {
    id: generateId(),
    title: "Sleep",
    day: "Thursday",
    startTime: "22:30",
    endTime: "06:30",
    category: "sleep",
  },

  // Friday
  {
    id: generateId(),
    title: "Breakfast",
    day: "Friday",
    startTime: "07:30",
    endTime: "08:00",
    category: "meal",
  },
  {
    id: generateId(),
    title: "Algorithms Exam Prep",
    day: "Friday",
    startTime: "08:00",
    endTime: "10:00",
    category: "study",
    priority: 10,
  },
  {
    id: generateId(),
    title: "Algorithms Class",
    day: "Friday",
    startTime: "10:30",
    endTime: "12:30",
    category: "class",
    location: "Lecture Hall A",
  },
  {
    id: generateId(),
    title: "Lunch",
    day: "Friday",
    startTime: "13:00",
    endTime: "14:00",
    category: "meal",
  },
  {
    id: generateId(),
    title: "Light Review",
    day: "Friday",
    startTime: "14:30",
    endTime: "16:00",
    category: "study",
  },
  {
    id: generateId(),
    title: "Weekend Wind-down",
    day: "Friday",
    startTime: "18:00",
    endTime: "20:00",
    category: "personal",
  },
  {
    id: generateId(),
    title: "Dinner",
    day: "Friday",
    startTime: "20:00",
    endTime: "21:00",
    category: "meal",
  },

  // Saturday
  {
    id: generateId(),
    title: "Sleep In",
    day: "Saturday",
    startTime: "23:00",
    endTime: "08:30",
    category: "sleep",
  },
  {
    id: generateId(),
    title: "Brunch",
    day: "Saturday",
    startTime: "09:00",
    endTime: "10:00",
    category: "meal",
  },
  {
    id: generateId(),
    title: "Weekend Study Block",
    day: "Saturday",
    startTime: "10:30",
    endTime: "13:00",
    category: "study",
    priority: 8,
  },
  {
    id: generateId(),
    title: "Lunch",
    day: "Saturday",
    startTime: "13:00",
    endTime: "14:00",
    category: "meal",
  },
  {
    id: generateId(),
    title: "Personal Activities",
    day: "Saturday",
    startTime: "14:00",
    endTime: "18:00",
    category: "personal",
  },
  {
    id: generateId(),
    title: "Dinner",
    day: "Saturday",
    startTime: "18:30",
    endTime: "19:30",
    category: "meal",
  },
  {
    id: generateId(),
    title: "Review Week Notes",
    day: "Saturday",
    startTime: "20:00",
    endTime: "21:30",
    category: "study",
  },

  // Sunday
  {
    id: generateId(),
    title: "Rest / Sleep",
    day: "Sunday",
    startTime: "22:30",
    endTime: "07:30",
    category: "sleep",
  },
  {
    id: generateId(),
    title: "Late Breakfast",
    day: "Sunday",
    startTime: "08:00",
    endTime: "09:00",
    category: "meal",
  },
  {
    id: generateId(),
    title: "Week Planning",
    day: "Sunday",
    startTime: "09:30",
    endTime: "10:30",
    category: "personal",
  },
  {
    id: generateId(),
    title: "Deep Study - Calculus",
    day: "Sunday",
    startTime: "11:00",
    endTime: "13:30",
    category: "study",
    priority: 9,
  },
  {
    id: generateId(),
    title: "Lunch",
    day: "Sunday",
    startTime: "13:30",
    endTime: "14:30",
    category: "meal",
  },
  {
    id: generateId(),
    title: "Rest & Recharge",
    day: "Sunday",
    startTime: "14:30",
    endTime: "17:00",
    category: "personal",
  },
  {
    id: generateId(),
    title: "Programming Review",
    day: "Sunday",
    startTime: "17:00",
    endTime: "19:00",
    category: "study",
    priority: 8,
  },
  {
    id: generateId(),
    title: "Dinner",
    day: "Sunday",
    startTime: "19:30",
    endTime: "20:30",
    category: "meal",
  },
  {
    id: generateId(),
    title: "Prep for Monday",
    day: "Sunday",
    startTime: "21:00",
    endTime: "22:00",
    category: "personal",
  },
];

/** Sample priority items */
export const SAMPLE_PRIORITIES: PriorityItem[] = [
  {
    id: generateId(),
    subject: "Algorithms & Data Structures",
    priority: 10,
    reason: "Final exam in 3 weeks, very challenging topic",
    hoursPerWeek: 8,
    color: "#a855f7",
  },
  {
    id: generateId(),
    subject: "Calculus II",
    priority: 9,
    reason: "Midterm next week, struggling with integration",
    hoursPerWeek: 6,
    color: "#3b82f6",
  },
  {
    id: generateId(),
    subject: "Physics (Mechanics)",
    priority: 9,
    reason: "Complex concepts, need extra practice",
    hoursPerWeek: 5,
    color: "#22c55e",
  },
  {
    id: generateId(),
    subject: "Programming",
    priority: 8,
    reason: "Project due in 2 weeks",
    hoursPerWeek: 5,
    color: "#f59e0b",
  },
  {
    id: generateId(),
    subject: "Statistics",
    priority: 7,
    reason: "Important for data analysis skills",
    hoursPerWeek: 4,
    color: "#f472b6",
  },
];
